safely_report/survey/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required, login_user
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import StaleDataError

from safely_report.auth.utils import logout_and_clear, role_required
from safely_report.models import GlobalState, Respondent, Role, User, db
from safely_report.settings import XLSFORM_PATH
from safely_report.survey.form_generator import SurveyFormGenerator
from safely_report.survey.garbling import Garbler
from safely_report.survey.survey_processor import SurveyProcessor

# Instantiate classes for conducting the survey
survey_processor = SurveyProcessor(XLSFORM_PATH, session)
garbler = Garbler(XLSFORM_PATH, db)
form_generator = SurveyFormGenerator(survey_processor, garbler)


survey_blueprint = Blueprint("survey", __name__)


@survey_blueprint.before_request
@login_required
def require_auth():
    pass  # Actual implementation handled by decorator


@survey_blueprint.before_request
def handle_nonactive_survey():
    if not GlobalState.is_survey_active():
        if current_user.role == Role.Respondent:
            current_app.logger.warning(
                "Access attempted at non-active survey "
                f"- user {current_user.id}"
            )
            flash("Survey is currently unavailable", "error")
            return redirect(url_for("index"))


@survey_blueprint.context_processor
def inject_template_variables():
    return {"is_testing_mode": current_user.role != Role.Respondent}


@survey_blueprint.errorhandler(IntegrityError)
def handle_response_resubmission(e):
    current_app.logger.warning(f"Resubmission tried - user {current_user.id}")
    flash("A response has already been submitted.", "error")
    return redirect(request.referrer or url_for("survey.index"))


@survey_blueprint.errorhandler(StaleDataError)
def handle_concurrency_conflict(e):
    current_app.logger.warning(
        "Failed submission due to concurrency conflict "
        "- user {current_user.id}"
    )
    flash(
        "Sorry - we were unable to record your response. Please try again.",
        "warning",
    )
    return redirect(request.referrer or url_for("survey.index"))


@survey_blueprint.route("/", methods=["GET", "POST"])
def index():
    if survey_processor.curr_survey_end:
        return render_template("survey/submit.html")

    if survey_processor.curr_survey_start:
        survey_processor.next()  # Roll forward to first displayable element

    form = form_generator.make_curr_form()

    if form.validate_on_submit():
        survey_processor.next()
        return redirect(url_for("survey.index"))

    return render_template("survey/index.html", form=form)


@survey_blueprint.route("/back")
def back():
    # Ensure full "refresh" by moving back twice and forward once
    survey_processor.back()
    if not survey_processor.curr_survey_start:
        survey_processor.back()
    survey_processor.next()

    return redirect(url_for("survey.index"))


@survey_blueprint.route("/exit")
def exit():
    if current_user.role == Role.Respondent:
        id = current_user.id
        logout_and_clear()
        current_app.logger.info(f"Survey exit - user {id}")
    else:
        survey_processor.clear_data()

    return redirect(url_for("index"))


@survey_blueprint.route("/submit")
def submit():
    if not survey_processor.curr_survey_end:
        return redirect(url_for("survey.index"))

    if current_user.role != Role.Respondent:
        survey_processor.clear_data()
        return redirect(url_for("index"))

    garbler.garble_and_store(
        survey_response=survey_processor.gather_survey_response(),
        respondent_uuid=current_user.uuid,
        enumerator_uuid=survey_processor.enumerator_uuid,
    )

    current_app.logger.info(f"Response submitted - user {current_user.id}")

    logout_and_clear()

    flash("Response submitted successfully", "success")
    return redirect(url_for("index"))


@role_required(Role.Enumerator)
@survey_blueprint.route("/on-behalf-of/<respondent_id>")
def on_behalf_of(respondent_id: int):
    """
    Let enumerator access survey on behalf of their assigned respondent.
    """
    enumerator_uuid = current_user.uuid

    respondent = Respondent.query.filter_by(id=respondent_id).first()
    if respondent is not None:
        if respondent.enumerator_uuid == enumerator_uuid:
            user = User.query.filter_by(uuid=respondent.uuid).first()
            if user is not None:
                logout_and_clear()
                login_user(user)
                survey_processor.set_enumerator_uuid(enumerator_uuid)
                current_app.logger.info(f"Delegated login for user {user.id}")
                return redirect(url_for("survey.index"))

    current_app.logger.warning(f"Failed delegated login for user {user.id}")
    flash("Respondent not found", "error")
    return redirect(url_for("enumerator.index"))

safely_report/templates/survey/index.html
{% extends "survey/layout.html" %}

{% block content %}

{{ super() }}

<div class="form-container">
  {# Display garbling info in a collapsible accordion box #}
  {% if form.meta.garbling_params %}
    {# Extract and format garbling parameters #}
    {% set garbling_params = form.meta.garbling_params %}
    {% set choices = dict(form.field.choices) %}
    {% set garbling_answer = choices[garbling_params.answer] %}
    {% set garbling_percent = (garbling_params.rate * 100) | int %}
    {% set garbling_covariate = garbling_params.covariate %}
    <div class="alert alert-light border-2">
      <div class="accordion-button">
        <i class="bi bi-info-circle" style="font-size: x-large; color: cornflowerblue;"></i>
        <span class="px-4">
          This question uses "garbling"
          to keep your response private.
        </span>
      </div>
      <hr>
      <div class="accordion-body">
        {% if garbling_covariate %}
          {# Show message for block garbling #}
          This survey question is designed to guarantee that
          at least {{ garbling_percent }}% of recorded responses
          will be "{{ garbling_answer }}". We do so by having
          the application automatically switch {{ garbling_percent }}%
          of responses to "{{ garbling_answer }}".
          <br>
          <br>
          Hence, if we record your response as "{{ garbling_answer }}",
          no one can really know for sure whether you truly responded
          "{{ garbling_answer }}" or whether the application switched
          your response to "{{ garbling_answer }}". This keeps your
          information very private.
        {% else %}
          {# Show message for IID garbling #}
          This survey question randomly switches your response to
          "{{ garbling_answer }}" with {{ garbling_percent }}% chance.
          Hence, if we record your response as "{{ garbling_answer }}",
          no one can really know for sure whether you truly responded
          "{{ garbling_answer }}" or whether your response was randomly
          switched to "{{ garbling_answer }}". This keeps your
          information very private.
        {% endif %}
      </div>
    </div>
  {% endif %}


  <div class="container" style="display: flex;">
  <!-- Media container -->


    {% if form.meta.media %}
      <div class="form-container">
      {{ form.meta.media.html|safe }}
      </div>
    <form method="POST" class="form-content bg-light p-4 rounded">
      {% else %}
    <!-- Apply 'full-width' class when media is absent -->
    <form method="POST" class="form-content bg-light p-4 rounded full-width">
   {% endif %}
    {{ form.hidden_tag() }}
    {# Display errors if any #}
    {% if form.field.errors %}
      {% for message in form.field.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    {# Display form content #}
    <div class="mb-3">
      {{ form.field.label.text|safe }}
      {% if form.field.description %}
        <small class="text-muted">{{ form.field.description }}</small>
      {% endif %}
      {% if form.field.widget %}
        {{ form.field(class="form-control") }}
      {% endif %}
    </div>
    {# Display buttons #}
    <div class="d-flex justify-content-between">
      <a href="{{ url_for('survey.back') }}" class="btn btn-secondary">Back</a>
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
</div>
</div>
{% endblock %}

safely_report/templates/survey/layout.html
{% extends "base.html" %}

{% block content %}

  {{ super() }}

  {% if is_testing_mode %}
    <div class="alert alert-info text-center" role="alert">
      TESTING MODE: Response will not be stored
    </div>
  {% endif %}

  {% if not is_testing_mode %}
    <div class="alert alert-info text-center" role="alert">
      NOTE: Leaving the survey without submitting will result in lost responses
    </div>
  {% endif %}

  <div class="d-flex justify-content-center">
    {% set message = "Sure to exit? Progress will not be saved." %}
    <a
      href="{{ url_for('survey.exit') }}"
      class="btn btn-link btn-sm"
      onclick="return confirm('{{ message }}')"
    >
      Exit
    </a>
  </div>

{% endblock %}

safely_report/templates/survey/run_survey.html
{% extends "base.html" %}

{% block content %}

{# <!-- FOR DEBUGGING -->
<ul>
  <li>Element Name: {{ survey_processor.curr_name }}</li>
  <li>Element Type: {{ survey_processor.curr_type }}</li>
  <li>Language Selected: {{ survey_processor.curr_lang }}</li>
  <li>Language Options: {{ survey_processor.curr_lang_options }}</li>
  <li>Label: {{ survey_processor.curr_label }}</li>
  <li>Hint: {{ survey_processor.curr_hint }}</li>
</ul> #}

<div class="form-container">
  <form method="POST" class="bg-light p-4 rounded">
    {{ form.hidden_tag() }}
    {% if form.field.errors %}
      {% for message in form.field.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="mb-3">
      {{ form.field.label(class="form-label") }}
      {% if form.field.description %}
        <small class="text-muted">{{ form.field.description }}</small>
      {% endif %}
      {% if form.field.widget %}
        {{ form.field(class="form-control") }}
      {% endif %}
    </div>
    <div class="d-flex justify-content-between">
      <a href="{{ url_for('survey.back') }}" class="btn btn-secondary">Back</a>
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
</div>

{% endblock %}

safely_report/templates/survey/submit.html
{% extends "survey/layout.html" %}

{% block content %}

{{ super() }}

<div class="form-container">
  <div class="bg-light p-4 rounded">
    <h2 class="mb-4">Congratulations!</h2>
    <div class="mb-4">You have reached survey end. Are you ready to submit?</div>
    <div class="d-flex justify-content-between">
      <a href="{{ url_for('survey.back') }}" class="btn btn-secondary">Cancel</a>
      <a href="{{ url_for('survey.submit') }}" class="btn btn-primary">Submit</a>
    </div>
  </div>
</div>

{% endblock %}

safely_report/templates/survey/submit_survey.html
{% extends "base.html" %}

{% block content %}

<div class="form-container">
  <div class="bg-light p-4 rounded">
    <h2 class="mb-4">Congratulations!</h2>
    <div class="mb-4">You have reached survey end. Are you ready to submit?</div>
    <div class="d-flex justify-content-between">
      <a href="{{ url_for('survey.back') }}" class="btn btn-secondary">Cancel</a>
      <a href="{{ url_for('survey.submit') }}" class="btn btn-primary">Submit</a>
    </div>
  </div>
</div>

{% endblock %}