safely_report/enumerator/views.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required

from safely_report.auth.utils import role_required
from safely_report.models import Respondent, Role

enumerator_blueprint = Blueprint("enumerator", __name__)


@enumerator_blueprint.before_request
@login_required
@role_required(Role.Enumerator)
def require_auth():
    pass  # Actual implementation handled by decorator


@enumerator_blueprint.route("/")
def index():
    # List respondent attributes to display
    attributes = Respondent.__table__.columns.keys()
    attributes_to_hide = ["uuid", "enumerator_uuid", "id", "response_status"]
    attributes_to_show = [a for a in attributes if a not in attributes_to_hide]

    # Retrieve assigned respondent records
    respondents = (
        Respondent.query.filter_by(enumerator=current_user)
        .order_by(Respondent.response_status.desc())  # Incomplete first
        .all()
    )

    return render_template(
        "enumerator/index.html",
        attributes=attributes_to_show,
        respondents=respondents,
    )

safely_report/survey/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import current_user, login_required, login_user
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import StaleDataError

from safely_report.auth.utils import logout_and_clear, role_required
from safely_report.models import GlobalState, Respondent, Role, User, db
from safely_report.settings import XLSFORM_PATH
from safely_report.survey.form_generator import SurveyFormGenerator
from safely_report.survey.garbling import Garbler
from safely_report.survey.survey_processor import SurveyProcessor

# Instantiate classes for conducting the survey
survey_processor = SurveyProcessor(XLSFORM_PATH, session)
garbler = Garbler(XLSFORM_PATH, db)
form_generator = SurveyFormGenerator(survey_processor, garbler)


survey_blueprint = Blueprint("survey", __name__)


@survey_blueprint.before_request
@login_required
def require_auth():
    pass  # Actual implementation handled by decorator


@survey_blueprint.before_request
def handle_nonactive_survey():
    if not GlobalState.is_survey_active():
        if current_user.role == Role.Respondent:
            current_app.logger.warning(
                "Access attempted at non-active survey "
                f"- user {current_user.id}"
            )
            flash("Survey is currently unavailable", "error")
            return redirect(url_for("index"))


@survey_blueprint.context_processor
def inject_template_variables():
    return {"is_testing_mode": current_user.role != Role.Respondent}


@survey_blueprint.errorhandler(IntegrityError)
def handle_response_resubmission(e):
    current_app.logger.warning(f"Resubmission tried - user {current_user.id}")
    flash("A response has already been submitted.", "error")
    return redirect(request.referrer or url_for("survey.index"))


@survey_blueprint.errorhandler(StaleDataError)
def handle_concurrency_conflict(e):
    current_app.logger.warning(
        "Failed submission due to concurrency conflict "
        "- user {current_user.id}"
    )
    flash(
        "Sorry - we were unable to record your response. Please try again.",
        "warning",
    )
    return redirect(request.referrer or url_for("survey.index"))


@survey_blueprint.route("/", methods=["GET", "POST"])
def index():
    if survey_processor.curr_survey_end:
        return render_template("survey/submit.html")

    if survey_processor.curr_survey_start:
        survey_processor.next()  # Roll forward to first displayable element

    form = form_generator.make_curr_form()

    if form.validate_on_submit():
        survey_processor.next()
        return redirect(url_for("survey.index"))

    return render_template("survey/index.html", form=form)


@survey_blueprint.route("/back")
def back():
    # Ensure full "refresh" by moving back twice and forward once
    survey_processor.back()
    if not survey_processor.curr_survey_start:
        survey_processor.back()
    survey_processor.next()

    return redirect(url_for("survey.index"))


@survey_blueprint.route("/exit")
def exit():
    if current_user.role == Role.Respondent:
        id = current_user.id
        logout_and_clear()
        current_app.logger.info(f"Survey exit - user {id}")
    else:
        survey_processor.clear_data()

    return redirect(url_for("index"))


@survey_blueprint.route("/submit")
def submit():
    if not survey_processor.curr_survey_end:
        return redirect(url_for("survey.index"))

    if current_user.role != Role.Respondent:
        survey_processor.clear_data()
        return redirect(url_for("index"))

    garbler.garble_and_store(
        survey_response=survey_processor.gather_survey_response(),
        respondent_uuid=current_user.uuid,
        enumerator_uuid=survey_processor.enumerator_uuid,
    )

    current_app.logger.info(f"Response submitted - user {current_user.id}")

    logout_and_clear()

    flash("Response submitted successfully", "success")
    return redirect(url_for("index"))


@role_required(Role.Enumerator)
@survey_blueprint.route("/on-behalf-of/<respondent_id>")
def on_behalf_of(respondent_id: int):
    """
    Let enumerator access survey on behalf of their assigned respondent.
    """
    enumerator_uuid = current_user.uuid

    respondent = Respondent.query.filter_by(id=respondent_id).first()
    if respondent is not None:
        if respondent.enumerator_uuid == enumerator_uuid:
            user = User.query.filter_by(uuid=respondent.uuid).first()
            if user is not None:
                logout_and_clear()
                login_user(user)
                survey_processor.set_enumerator_uuid(enumerator_uuid)
                current_app.logger.info(f"Delegated login for user {user.id}")
                return redirect(url_for("survey.index"))

    current_app.logger.warning(f"Failed delegated login for user {user.id}")
    flash("Respondent not found", "error")
    return redirect(url_for("enumerator.index"))

safely_report/templates/enumerator/index.html
{% extends "base.html" %}

{% block content %}

{{ super() }}

<div class="container mt-5">
  <div class="d-flex justify-content-between mb-4">
    <a href="{{ url_for('survey.index') }}" class="btn btn-outline-primary">Test the survey</a>
    <a
      href="{{ url_for('auth.logout') }}"
      class="btn btn-link"
      onclick="return confirm('Sure to log out?')"
    >
      Logout
    </a>
  </div>

  <h1 class="text-center mb-4">Assigned Respondents</h1>

  <table class="table table-bordered table-hover">
    <thead class="table-dark">
      <tr class="text-center align-middle">
        {% for attr in attributes %}
          <th>{{ attr|replace("_", " ")|title }}</th>
        {% endfor %}
        <th>Survey</th>
      </tr>
    </thead>
    <tbody>
      {% for resp in respondents %}
        <tr class="text-center align-middle">
          {% for attr in attributes %}
            <td>{{ resp[attr] }}</td>
          {% endfor %}
          <td>
            {% if resp.has_completed_response() %}
              Done
            {% else %}
              {% set disabled = "" if is_survey_active else "disabled"%}
              {% set message = "Sure to start survey for the selected respondent?" %}
              <a
                href="{{ url_for('survey.on_behalf_of', respondent_id=resp.id) }}"
                class="btn btn-sm btn-outline-success {{ disabled }}"
                onclick="return confirm('{{ message }}')"
              >
                Start
              </a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}